### ISSUE TITLE
Unable to access combatHistory data for ModernWarfare2 or any other game title

### ISSUE THREAD

**Issue by khatzopoulos** [TodoLodo2089/cod-python-api#19]
**Describe the bug**
Unable to access combatHistory data for any of the game titles, result produces the following: {'status': 'success', 'data': {}}

**To Reproduce**
1. Run the following code to obtain combatHistory for ModernWarfare2 (or any game title):

`
from cod_api import API, platforms
import asyncio

api = API()

api.login('sso_token') #this has been replaced with my account sso_cookie

profile = api.ModernWarfare2.combatHistory(platforms.Battlenet, "Username#1234") #this has been replaced with my username

print(profile)
`

2. After running this code with my username and SSO token correctly inserted I receive the results {'status': 'success', 'data': {}}
3. I have ensured my username and sso_token are correct by running fullData instead of combat history and had data returned

**Expected behavior**
After ensuring my sso_token and username are correct by running other parameters such as fullData and getting data returned and playing the game extensively on this account, I would expect the combat history for ModernWarfare2, or any other game, to be returned. I would like to take this combat history data and dashboard my own combat record, with more insightful metrics than what is provided from the standard combat record provided by Call of Duty in game.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Windows 10

**Additional context**
Please let me know if there is a bug in my code or if I am misunderstanding some aspects. My end goal would be to receieve my raw, per game combat history

**Comment by aaron-fredrick** [comment]
Sorry for overlooking this issue, we have been directing most issues on our discord and at the time of this issue was posted the api endpoint weren't active and as for now it would be, if any further issues rise feel free to open a new issue

Thanks
