### ISSUE TITLE
See KdRatio Live Party

### ISSUE THREAD

**Issue by Sandaxxx** [TodoLodo2089/cod-python-api#21]
Being able to see the KdRatio of the game we joined

**Comment by aaron-fredrick** [comment]
for a given match history, the k/d ratio is given in the json data
Does this answer your issue?

**Comment by Engineer152** [comment]
The average KD ratio for a lobby will need to be generated on the user side by cycling though each users profile KD endpoint to gather all KDs. The match endpoint does not have the average KD alone.
