### ISSUE TITLE
Authentication fails (Platform: Activision)

### ISSUE THREAD

**Issue by farhanghazi97** [TodoLodo2089/cod-python-api#23]
**To reproduce**:

```
api = API()
api.login('<sso_token_goes_here>')
data = api.ModernWarfare2.fullData(gamertag="<username goes here>", platform=platforms.Activision)
return JsonResponse({"stats": data})
```

The above code is part of an API endpoint on my server that is invoked via GET. Testing it with Postman yields the following response: 

```
{
    'status': 'error', 
    'data': {
        'type": 'com.activision.mt.common.stdtools.exceptions.NoStackTraceException', 
        'message': 'Error from datastore'
    }
}
```

**Expected behavior**
The above endpoint with the correct credentials (i.e SSO token) should yield a successful response.

**Desktop (please complete the following information):**
 - OS: Ubuntu 220.4 (Python3.10)
 - Browser: Chrome 
 - Version 110.0.5481.77 

**Additional context**
I have confirmed that I am using:

- the correct ACT_SSO_TOKEN as obtained from <a>https://www.callofduty.com/au/en/</a>  
- correct gamertag for my chosen platform (Activision)

**Comment by farhanghazi97** [comment]
I've been advised via Discord that the API server is currently down. It will be back up around 15th Feb, 2023 (tentative).

**Comment by aaron-fredrick** [comment]
Yes you have been advised correctly, the response isnt an error but the response given by the end point
Keep yourself updated at our discord server
