### ISSUE TITLE
ModernWarfare2 and Warzone2 returns empty value of json

### ISSUE THREAD

**Issue by ChesterLee65535** [TodoLodo2089/cod-python-api#24]
As title.

**Comment by RyonGerringer** [comment]
I believe that call of duty does not provide these yet, someone else may provide more info.

**Comment by aaron-fredrick** [comment]
As for now the endpoint does not give any expected successful response but in an earlier discussion in our discord server backed with test runs it was found out that some profiles (mostly in psn platform) privacy is set to private hence data returns as an empty json
